### ISSUE TITLE
Server error: Uncaught internal server error.

### ISSUE THREAD

**Issue by dimitar-github** [parse-community/parse-server-example#213]
I've installed the Parse-server on my local. also connected with migrated mLab database. I've faced a server issue while running the original iOS app. (which using Parse SDK 1.13.0)

Following is whole error description.

error: Uncaught internal server error. TypeError: Cannot read property 'type' of undefined
    at /usr/local/lib/node_modules/parse-server/lib/Controllers/SchemaController.js:784:38
    at Array.filter (native)
    at /usr/local/lib/node_modules/parse-server/lib/Controllers/SchemaController.js:783:39
    at SchemaController.getRelationFields (/usr/local/lib/node_modules/parse-server/lib/Controllers/SchemaController.js:794:10)
    at Object.untransformObject (/usr/local/lib/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoTransform.js:892:37)
    at DatabaseController.untransformObject (/usr/local/lib/node_modules/parse-server/lib/Controllers/DatabaseController.js:145:31)
    at /usr/local/lib/node_modules/parse-server/lib/Controllers/DatabaseController.js:819:29
    at Array.map (native)
    at /usr/local/lib/node_modules/parse-server/lib/Controllers/DatabaseController.js:818:33
    at run (/usr/local/lib/node_modules/parse-server/node_modules/core-js/modules/es6.promise.js:89:22) TypeError: Cannot read property 'type' of undefined
    at /usr/local/lib/node_modules/parse-server/lib/Controllers/SchemaController.js:784:38
    at Array.filter (native)
    at /usr/local/lib/node_modules/parse-server/lib/Controllers/SchemaController.js:783:39
    at SchemaController.getRelationFields (/usr/local/lib/node_modules/parse-server/lib/Controllers/SchemaController.js:794:10)
    at Object.untransformObject (/usr/local/lib/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoTransform.js:892:37)
    at DatabaseController.untransformObject (/usr/local/lib/node_modules/parse-server/lib/Controllers/DatabaseController.js:145:31)
    at /usr/local/lib/node_modules/parse-server/lib/Controllers/DatabaseController.js:819:29
    at Array.map (native)
    at /usr/local/lib/node_modules/parse-server/lib/Controllers/DatabaseController.js:818:33
    at run (/usr/local/lib/node_modules/parse-server/node_modules/core-js/modules/es6.promise.js:89:22)

Any solution for this?

**Comment by dimitar-github** [comment]
Can I get any response please?

**Comment by mneill01** [comment]
I am having a very similar issue myself. However my exception is citing an undefined variable called "atom". It's apparent that this template is missing a key component to get MongoDB connections to work in Cloud Code

Uncaught internal server error. [ReferenceError: atom is not defined] ReferenceError: atom is not defined
    at /usr/local/lib/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoTransform.js:559:78
    at Array.map (native)
    at transformConstraint (/usr/local/lib/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoTransform.js:556:29)
    at transformQueryKeyValue (/usr/local/lib/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoTransform.js:193:7)
    at transformWhere (/usr/local/lib/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoTransform.js:215:15)
    at /usr/local/lib/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoTransform.js:168:18
    at Array.map (native)
    at transformQueryKeyValue (/usr/local/lib/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoTransform.js:167:41)
    at transformWhere (/usr/local/lib/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoTransform.js:215:15)
    at MongoStorageAdapter.find (/usr/local/lib/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoStorageAdapter.js:321:59)

**Comment by jenrique7** [comment]
Same here:

Uncaught internal server error. [TypeError: Cannot convert undefined or null to object] TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at transformInteriorValue (/var/app/current/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoTransform.js:104:100)
    at /var/app/current/node_modules/parse-server/node_modules/lodash/lodash.js:12739:23
    at /var/app/current/node_modules/parse-server/node_modules/lodash/lodash.js:4411:15
    at baseForOwn (/var/app/current/node_modules/parse-server/node_modules/lodash/lodash.js:2654:24)
    at Function.mapValues (/var/app/current/node_modules/parse-server/node_modules/lodash/lodash.js:12738:7)
    at parseObjectKeyValueToMongoObjectKeyValue (/var/app/current/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoTransform.js:296:28)
    at parseObjectToMongoObjectForCreate (/var/app/current/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoTransform.js:308:33)
    at MongoStorageAdapter.createObject (/var/app/current/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoStorageAdapter.js:242:79)
    at /var/app/current/node_modules/parse-server/lib/Controllers/DatabaseController.js:518:29
    at run (/var/app/current/node_modules/parse-server/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:89:22)
    at /var/app/current/node_modules/parse-server/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/var/app/current/node_modules/parse-server/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:18:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickDomainCallback (node.js:390:13)

**Comment by pmaganti** [comment]
#2029

**Comment by pmaganti** [comment]
I ran into same issue. 
https://github.com/ParsePlatform/parse-server/pull/2029

Seen the above pull request was merged. Run
`npm update parse-server --save`

This should work.

**Comment by ogonzalezadell** [comment]
Hi, I also have the same error as @mneill01, 
We have a RHEL 6.4 environment where everything works fin but this issue. We are using: 
- `Node 4.3`,
- `Mongo 3.0.11`
- `parse-server 2.2.15`

The parse logs show the following error:

`2016-07-08T07:15:10.308Z - Uncaught internal server error. [ReferenceError: atom is not defined] ReferenceError: atom is not defined
    at /home/user/parse-server/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoTransform.js:499:78
    at Array.map (native)
    at transformConstraint (/home/user/parse-server/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoTransform.js:496:29)
    at transformQueryKeyValue (/home/user/parse-server/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoTransform.js:193:7)
    at transformWhere (/home/user/parse-server/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoTransform.js:215:15)
    at MongoStorageAdapter.find (/home/user/parse-server/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoStorageAdapter.js:412:59)
    at /home/user/parse-server/node_modules/parse-server/lib/Controllers/DatabaseController.js:923:36
    at run (/home/user/parse-server/node_modules/parse-server/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:89:22)
    at /home/user/parse-server/node_modules/parse-server/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/home/user/parse-server/node_modules/parse-server/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:18:9)`

Failing in a complex query "URL" where we try to find posts where the post.user (pointer) is $in an array (of pointers of type user) users [Note: I use REST Services, not the SDK, the decoded url below is the url that the error from server gives back to my app]:

` domain.com/parse/classes/Post?include=user,user.region,user.dptArea&limit=100&order=-createdAt&where[user][$in][][__type]=Pointer&where[user][$in][][className]=_User&where[user][$in][][objectId]=4dyTOMTLZP&where[user][$in][][__type]=Pointer&where[user][$in][][className]=_User&where[user][$in][][objectId]=1fZ3gzNivG`

Also parsing the error I get:` Error code 1`, `error message (null)`, probably because it is a internal server error.
