### ISSUE TITLE
After Send push request by RESTAPI,  Parse-server-example throw exception.

### ISSUE THREAD

**Issue by dasheng2016** [parse-community/parse-server-example#251]
follow is exception:
2016-08-02T10:58:46.583924+00:00 app[web.1]: error: Uncaught internal server error. [Error: Can't set headers after they are sent.] Error: Can't set headers after they are sent.
2016-08-02T10:58:46.583941+00:00 app[web.1]:     at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
2016-08-02T10:58:46.583943+00:00 app[web.1]:     at expressInit (/app/node_modules/parse-server/node_modules/express/lib/middleware/init.js:23:42)
2016-08-02T10:58:46.583944+00:00 app[web.1]:     at Layer.handle [as handle_request](/app/node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)
2016-08-02T10:58:46.583945+00:00 app[web.1]:     at trim_prefix (/app/node_modules/parse-server/node_modules/express/lib/router/index.js:312:13)
2016-08-02T10:58:46.583946+00:00 app[web.1]:     at /app/node_modules/parse-server/node_modules/express/lib/router/index.js:280:7
2016-08-02T10:58:46.583947+00:00 app[web.1]:     at Function.process_params (/app/node_modules/parse-server/node_modules/express/lib/router/index.js:330:12)
2016-08-02T10:58:46.583947+00:00 app[web.1]:     at next (/app/node_modules/parse-server/node_modules/express/lib/router/index.js:271:10)
2016-08-02T10:58:46.583948+00:00 app[web.1]:     at query (/app/node_modules/parse-server/node_modules/express/lib/middleware/query.js:44:5)
2016-08-02T10:58:46.583949+00:00 app[web.1]:     at Layer.handle [as handle_request](/app/node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)
2016-08-02T10:58:46.583950+00:00 app[web.1]:     at trim_prefix (/app/node_modules/parse-server/node_modules/express/lib/router/index.js:312:13)
2016-08-02T10:58:46.584847+00:00 app[web.1]: Error: Can't set headers after they are sent.
2016-08-02T10:58:46.584848+00:00 app[web.1]:     at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
2016-08-02T10:58:46.584848+00:00 app[web.1]:     at ServerResponse.header (/app/node_modules/express/lib/response.js:695:10)
2016-08-02T10:58:46.584849+00:00 app[web.1]:     at ServerResponse.send (/app/node_modules/express/lib/response.js:146:12)
2016-08-02T10:58:46.584849+00:00 app[web.1]:     at ServerResponse.json (/app/node_modules/express/lib/response.js:235:15)
2016-08-02T10:58:46.584850+00:00 app[web.1]:     at handleParseErrors (/app/node_modules/parse-server/lib/middlewares.js:255:9)
2016-08-02T10:58:46.584850+00:00 app[web.1]:     at Layer.handle_error (/app/node_modules/parse-server/node_modules/express/lib/router/layer.js:71:5)
2016-08-02T10:58:46.584851+00:00 app[web.1]:     at trim_prefix (/app/node_modules/parse-server/node_modules/express/lib/router/index.js:310:13)
2016-08-02T10:58:46.584851+00:00 app[web.1]:     at /app/node_modules/parse-server/node_modules/express/lib/router/index.js:280:7
2016-08-02T10:58:46.584852+00:00 app[web.1]:     at Function.process_params (/app/node_modules/parse-server/node_modules/express/lib/router/index.js:330:12)
2016-08-02T10:58:46.584852+00:00 app[web.1]:     at next (/app/node_modules/parse-server/node_modules/express/lib/router/index.js:271:10)
2016-08-02T10:58:49.009471+00:00 app[web.1]: info: warning: error while sending push code=107, message=bad $in value

Is anyone happend ?

**Comment by bryanbartow** [comment]
This just happened to me, too. I've been able to send other pushes programmatically through my Parse Server instance, but I just started getting this error.
