### ISSUE TITLE
Error: EACCES: permission denied, Exit status 7

### ISSUE THREAD

**Issue by ptsparseserver** [parse-community/parse-server-example#304]
When I run after the command "npm start", it gives the following error sometimes. Sometimes it runs without any issues. I haven't updated any file or permissions on any file in parse-server-example project. I am running it on Mac Mini.

Mac-mini:parse-server-example username$ npm start

> parse-server-example@1.4.0 start /Users/username/git/parse-server-example
> node index.js

(node:1556) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
parse-server-example running on port 1337.
info: Parse LiveQuery Server starts running
/Users/username/git/parse-server-example/node_modules/parse-server/lib/ParseServer.js:425
            throw err;
            ^

Error: EACCES: permission denied, open '/Users/username/git/parse-server-example/logs/parse-server.info.2016-11-22'

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.1.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! parse-server-example@1.4.0 start: `node index.js`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the parse-server-example@1.4.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the parse-server-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs parse-server-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls parse-server-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/username/git/parse-server-example/npm-debug.log

**Comment by ptsparseserver** [comment]
In my npm-debug.log file, I found out this,

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.1.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.10.9
3 info using node@v7.1.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle parse-server-example@1.4.0~prestart: parse-server-example@1.4.0
6 silly lifecycle parse-server-example@1.4.0~prestart: no script for prestart, continuing
7 info lifecycle parse-server-example@1.4.0~start: parse-server-example@1.4.0
8 verbose lifecycle parse-server-example@1.4.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle parse-server-example@1.4.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/username/git/parse-server-example/node_modules/.bin:/usr/local/Cellar/node/7.1.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle parse-server-example@1.4.0~start: CWD: /Users/username/git/parse-server-example
11 silly lifecycle parse-server-example@1.4.0~start: Args: [ '-c', 'node index.js' ]
12 silly lifecycle parse-server-example@1.4.0~start: Returned: code: 7  signal: null
13 info lifecycle parse-server-example@1.4.0~start: Failed to exec start script
14 verbose stack Error: parse-server-example@1.4.0 start: `node index.js`
14 verbose stack Exit status 7
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid parse-server-example@1.4.0
16 verbose cwd /Users/username/git/parse-server-example
17 error Darwin 16.1.0
18 error argv "/usr/local/Cellar/node/7.1.0/bin/node" "/usr/local/bin/npm" "start"
19 error node v7.1.0
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error parse-server-example@1.4.0 start: `node index.js`
22 error Exit status 7
23 error Failed at the parse-server-example@1.4.0 start script 'node index.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the parse-server-example package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node index.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs parse-server-example
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls parse-server-example
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
