### ISSUE TITLE
Query on location distance

### ISSUE THREAD

**Issue by davilaeric** [parse-community/parse-server-example#344]
Hello, 

I've tried to do a query on location, and I get this error. I'm not sure what would cause it... I've launched my server using the heroku button. I try other filters and they don't seem to cause the error. (Noob here)

I get this error in swift:
{"code":1,"message":"Internal server error."} (Code: 1, Version: 1.14.4)
Optional("{\"code\":1,\"message\":\"Internal server error.\"}") 

My guess is that mongodb can't query on location? I don't know how to fix that though. 

2017-05-08T03:29:34.965Z - Uncaught internal server error. { MongoError: error processing query: ns=heroku_r6dg7cvc.CommentaryTree: $and
    _created_at $gt new Date(1494127774935)
    _rperm $in [ null "*" "a81FrGp2R3" ]
    GEONEAR  field=location maxdist=7.17619e-07 isNearSphere=1
Sort: {}
Proj: {}
 planner returned error: unable to find index for $geoNear query
    at Function.MongoError.create (/app/node_modules/mongodb-core/lib/error.js:31:11)
    at /app/node_modules/mongodb-core/lib/connection/pool.js:489:72
    at authenticateStragglers (/app/node_modules/mongodb-core/lib/connection/pool.js:435:16)
    at Connection.messageHandler (/app/node_modules/mongodb-core/lib/connection/pool.js:469:5)
    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:321:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)
  name: 'MongoError',
  message: 'error processing query: ns=heroku_r6dg7cvc.CommentaryTree: $and\n    _created_at $gt new Date(1494127774935)\n    _rperm $in [ null "*" "a81FrGp2R3" ]\n    GEONEAR  field=location maxdist=7.17619e-07 isNearSphere=1\nSort: {}\nProj: {}\n planner returned error: unable to find index for $geoNear query',
  waitedMS: 0,
  ok: 0,
  errmsg: 'error processing query: ns=heroku_r6dg7cvc.CommentaryTree: $and\n    _created_at $gt new Date(1494127774935)\n    _rperm $in [ null "*" "a81FrGp2R3" ]\n    GEONEAR  field=location maxdist=7.17619e-07 isNearSphere=1\nSort: {}\nProj: {}\n planner returned error: unable to find index for $geoNear query',
  code: 2 } MongoError: error processing query: ns=heroku_r6dg7cvc.CommentaryTree: $and
    _created_at $gt new Date(1494127774935)
    _rperm $in [ null "*" "a81FrGp2R3" ]
    GEONEAR  field=location maxdist=7.17619e-07 isNearSphere=1
Sort: {}
Proj: {}
 planner returned error: unable to find index for $geoNear query
    at Function.MongoError.create (/app/node_modules/mongodb-core/lib/error.js:31:11)
    at /app/node_modules/mongodb-core/lib/connection/pool.js:489:72
    at authenticateStragglers (/app/node_modules/mongodb-core/lib/connection/pool.js:435:16)
    at Connection.messageHandler (/app/node_modules/mongodb-core/lib/connection/pool.js:469:5)
    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:321:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)

**Comment by ZacharyKhan** [comment]
MongoDB simply stores the location data (latitude, longitude). The Parse Server, wherever you may be hosting it, is what consumes the data from MongoDB and serves the correct information back to the client. 

I believe it is not an issue with MongoDB but rather with the Parse Server itself. Are you using the Parse Server Example without any changes to the code? 

Some client side code would be useful too 👍

**Comment by brianyyz** [comment]
Hi there
Did you solve this ?  I'm using location in my app and it is working well. My server is hosted on Heroku and using Mongo.

Can you provide any client code ?

**Comment by crystalSETH** [comment]
Experiencing this issue as well. Hosted on Heroku, mongoDB. Only happens when I query location.

**Comment by lordjjl** [comment]
I'm getting this issue as well. It appears to only occur when I use compound queries:

 var searchQuery = PFQuery.orQuery(withSubqueries: [query, orQuery])

If I omit the compound query, the location query works perfectly.
